### ISSUE TITLE
démarer la partie de code

### ISSUE THREAD

**Issue by samira1-gh** [samira1-gh/renforcement#2]
- [x] l instalation du l'envirenement du travail

- [x] réalisation  html 

- [x] réalisation de scss

- [x] version desktop

- [x] version mobile

**Comment by youssefbm** [comment]
pas mal keep up

**Comment by youssefbm** [comment]
Le BEM n'est pas appliquer correctement. Essayez de le revoir.

**Comment by samira1-gh** [comment]
fineshed mobile version
